name = "dudu-datascience"
entry = "src/main.dd"

[cxx]
standard = "c++20"

[build]
dir = "build"

[include]
paths = ["src"]

[pkg]
libs = ["openblas"]

[targets.target_tensor_surface]
entry = "src/target_tensor_surface.dd"

[targets.target_advanced_indexing]
entry = "src/target_advanced_indexing.dd"

[targets.target_blas_backend]
entry = "src/target_blas_backend.dd"

[targets.target_gpu_backend]
entry = "src/target_gpu_backend.dd"

[targets.target_gpu_backend.pkg]
libs = ["OpenCL"]
